engines:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false

ratings:
  paths:
  - client/**
  - server/**

exclude_paths:
  - client/test/
  - client/dist/
  - test/
  - template/