module.exports = {
  'group tests': (client) => {
    client
      .resizeWindow(1280, 800)
      .url('http://localhost:8000')
      .waitForElementVisible('body', 1000)
      .setValue('input#email', 'abigail@gmail.com')
      .setValue('input#username', 'abigail')
      .setValue('input#password', 'abigail2000')
      .setValue('input#confirmpassword', 'abigail2000')
      .click('button#create-account')
      .pause(1000)
      .assert.urlEquals('http://localhost:8000/#/messageboard')
      .click('a.modal-trigger')
      .setValue('input#name', 'ade')
      .click('.modal-footer')
      .pause(1000)
      .assert.containsText('span#name-error', 'Group Name is too short'
      + ' (min of 5 characters')
      .pause(1000)
      .clearValue('input#name')
      .setValue('input#name', 'Matterhorn')
      .click('button#save-group')
      .pause(1000)
      .assert.elementPresent('a#matterhorn')
      .click('a#matterhorn')
      .assert.urlContains('http://localhost:8000/#/messageboard/group')
      .pause(2000)
      .click('a#edit-group')
      .pause(2000)
      .assert.visible('.modal-content')
      .setValue('input#name', ' Group')
      .click('button#save-group')
      .pause(1000)
      .waitForElementVisible('.toast-message', 2000)
      .assert.containsText('.toast-message', 'Group updated successfully')
      .pause(1000)
      .assert.containsText('a#matterhorn-group', 'Matterhorn Group')
      .pause(4000)
      .click('a#add-user')
      .pause(2000)
      .assert.urlContains('members')
      .assert.containsText('li.collection-item', 'abigail')
      .setValue('input#search', 'sh')
      .click('button#search')
      .pause(2000)
      .assert.visible('ul#search-results')
      .click('a.non-members')
      .pause(1000)
      .waitForElementVisible('.toast-message', 2000)
      .assert.containsText('.toast-message', 'User Added Successfully')
      .click('a#logout-button')
      .assert.urlEquals('http://localhost:8000/#/login')
      .end();
  }
};
